### ISSUE TITLE
About the shape

### ISSUE THREAD

**Issue by xuecheng990531** [JuliaWolleb/Diffusion-based-Segmentation#10]
assert x_t.shape == eps.shape
AssertionError

Do I need to change the learn_sigma=True?

**Comment by xuecheng990531** [comment]
I solved this problem yesterday and I think that when determining the x_t
shape and eps shape, I only need to determine whether their channel numbers are the same.

**Comment by sherrlockk** [comment]
How did you solve this problem？I'm having the same issue

**Comment by xuecheng990531** [comment]
时间太长了，我都忘记了哈哈
