### ISSUE TITLE
Question about save the generate mask

### ISSUE THREAD

**Issue by xuecheng990531** [JuliaWolleb/Diffusion-based-Segmentation#11]
`th.save(s, './results/'+str(slice_ID)+'_output'+str(i))`

1. I see that in segment_sample.py, the above code can be used to generate a mask. how exactly is this done, the resulting file cannot be opened.
2. The number of channels of S is 5, how to get the mask?

**Comment by JuliaWolleb** [comment]
1. the sample is the output of your diffusion model, which is saved as a torch tensor s. you can open it with _torch.load_.
2. the sample s should have a channel number of 1. This is the mask.

**Comment by xuecheng990531** [comment]
Thanks a lot
