### ISSUE TITLE
Have you ever encountered this problem when running segmentation_sample.py?

### ISSUE THREAD

**Issue by jaceqin** [JuliaWolleb/Diffusion-based-Segmentation#12]
sampling step 0
sampling step 900
sampling step 800
sampling step 700
sampling step 600
sampling step 500
sampling step 400
sampling step 300
sampling step 200
sampling step 100
sampling step 0
sampling step 900
sampling step 800
sampling step 700
sampling step 600
sampling step 500
sampling step 400
sampling step 300
sampling step 200
sampling step 100
sampling step 0
Traceback (most recent call last):
  File "segmentation_sample.py", line 127, in <module>
    main()
  File "segmentation_sample.py", line 71, in main
    b, path = next(data)  #should return an image from the dataloader "data"
  File "/home/x012/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/x012/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 560, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/x012/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
StopIteration

**Comment by JuliaWolleb** [comment]
Is it possible that you iterated through your whole test dataset?
I just realized that the line `while len(all_images) * args.batch_size < args.num_samples:` is always true, so your algorithm stops once all images of your dataloader are through

**Comment by jaceqin** [comment]
Hello, can you share codes for generating uncertainty map and code for the scores [ Dice,HD95, Jaccard Index ] you used?
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年11月2日 15:25
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [JuliaWolleb/Diffusion-based-Segmentation] Have you ever encountered this problem when running segmentation_sample.py? (Issue #12)


Is it possible that you iterated through your whole test dataset?
I just realized that the line while len(all_images) * args.batch_size < args.num_samples: is always true, so your algorithm stops once all images of your dataloader are through

―

**Comment by saisusmitha** [comment]
@jaceqin if you have figured out the solution to your question kindly share that code for generating the scores and maps. It would be really helpful.
