### ISSUE TITLE
I meet a memory question when i run this code?

### ISSUE THREAD

**Issue by Wanyidon** [JuliaWolleb/Diffusion-based-Segmentation#14]
I set the same parameters as you except the batch_size. i have set the batch size =1, however, the system still show CUDA error out of memory. My GPU is 1080ti

**Comment by JuliaWolleb** [comment]
this is weird, with a batch-size of 1 this should work. do you still have this error?

**Comment by MuqinZ** [comment]
Can you give me your E-mail. I want to talk about this Net-Model with you.
