### ISSUE TITLE
great job!

### ISSUE THREAD

**Issue by jaceqin** [JuliaWolleb/Diffusion-based-Segmentation#17]
Hello!
I want to ask if there is a final result graph after segmentation in your code? How is the intermediate process of the sampling process output?

**Comment by JuliaWolleb** [comment]
Hi
Actually I just saved the sampled segmentation masks for all images of my test set in a folder. This happens in line 105 of the file _./segmentation_sample.py_. I did all score computation then with these saved images. Is this what you meant by "intermediate process"?

**Comment by MuqinZ** [comment]
Hello!
Can you give me your E-mail. I want to talk about this Net-Model with you.I have some question about this

**Comment by jaceqin** [comment]
> 

jace_q@outlook.com
