### ISSUE TITLE
Time for training

### ISSUE THREAD

**Issue by sangdv** [JuliaWolleb/Diffusion-based-Segmentation#18]
How long does it take to training the model? I have one RTX 3090. I wonder if I can train the model within few days.

**Comment by JuliaWolleb** [comment]
Hi
This should be absolutely doable in 2D, it took me around 1.5 days.

**Comment by MuqinZ** [comment]
Hello!
Can you give me your E-mail. I want to talk about this Net-Model with you.I have some question about this
