### ISSUE TITLE
about the Brats Dataset

### ISSUE THREAD

**Issue by qb02su** [JuliaWolleb/Diffusion-based-Segmentation#22]
The original Brats Dataset are 3D slices, how you transform them to 2D slices like sample dataset

**Comment by JuliaWolleb** [comment]
As described in Section 3 of the paper, we slice the 3D MR scans in axial slices. Since tumors rarely occur on the upper or lower part of the brain, we exclude the lowest 80 slices and the uppermost 26 slices.

**Comment by saisusmitha** [comment]
@JuliaWolleb where is this - the exclusion of 80 and 26 slices happening in the code? kindly tell me
