### ISSUE TITLE
Does the sampling result include the original image and mask

### ISSUE THREAD

**Issue by guanzhenghua** [JuliaWolleb/Diffusion-based-Segmentation#33]
Thank you very much for providing the code.
Download BRAST2020 data set and preprocess it into (1,240,240) according to the method in the paper.
![image](https://user-images.githubusercontent.com/114739026/234461535-ce0b206b-d040-4025-9aaf-a142ce8ef9dc.png)

The training and sampling process were successfully carried out, but the sampling result was a little strange, including the original image and mask.Because the final image generated in the paper only has a mask.So I wonder if I'm doing something wrong. 
And here's the sampling result.
![image](https://user-images.githubusercontent.com/114739026/234461837-94334176-ca79-408e-b544-16052e5d95ca.png)
My sincere thanks to you again. and look forward to your reply.

**Comment by saisusmitha** [comment]
@guanzhenghua In the below-mentioned code - the sample is the output mask - and I think it's only output segmentation - I don't know how you are getting everything included. 

sample, x_noisy, org = sample_fn(
                model,
                (args.batch_size, 3, args.image_size, args.image_size), img,
                clip_denoised=args.clip_denoised,
                model_kwargs=model_kwargs,
            )
            
 Can you share the pre-processing code - the original 3D to 2d slice wise folder code.

**Comment by guanzhenghua** [comment]
@saisusmitha of course, it is easy to slice 3D to 2D, i will show the code later.
I processed the data in the author's way, From the picture, it should be fine.
I'm sure the data preprocessing is fine, but the result does include a mixture of the original and the segmentation, so i wonder and need the author's answer. Have you run this program successfully.
maybe we can talk more in email: guanzhenghua2022@email.szu.edu.cn
I am looking forward to your email.


import nibabel as nib
import os
import numpy as np

path_in = r'H:\数据\新建文件夹\BraTS2020_TrainingData\MICCAI_BraTS2020_TrainingData'
path_out = r"H:\数据\新建文件夹\BraTS2020_croped_240"
start_second = True
list_four = [0,1,2,3,4]
num = 0
for root, dirs, files in os.walk(path_in):#root表示文件夹路径，dirs为空，files文件夹里的文件名
    print(num)
    num+=1
    if start_second == False:#because the first root is not right,so use the "start_second" just for drop out it
        for i in range(26, 75):
            file_name = os.path.split(root)
            nii_four = os.listdir(root)  # 0 1 2 3 4

            sub_dir = os.path.join(path_out, file_name[-1])
            sub_dir_add = "{}{}".format(sub_dir,"_"+str(i))
            os.mkdir(sub_dir_add)



            for j in list_four:
                sample_raw = nib.load(os.path.join(root,nii_four[j]))
                affine = sample_raw.affine.copy()
                hdr = sample_raw.header.copy()
                sample_np = np.asarray(sample_raw.get_fdata())
                sample_np = sample_np[:, :, i]
                gen = nib.Nifti1Image(sample_np, affine, hdr)

                rename = nii_four[j].split(".")
                rename = "{}_{}{}".format(rename[0],i,rename[1])
                nib.save(gen, os.path.join(sub_dir_add,rename))

    start_second = False

**Comment by guanzhenghua** [comment]
@saisusmitha of course, it is easy to slice 3D to 2D, i will show the code later.
I processed the data in the author's way, From the picture, it should be fine.
I'm sure the data preprocessing is fine, but the result does include a mixture of the original and the segmentation, so i wonder and need the author's answer. Have you run this program successfully.
maybe we can talk more in email: guanzhenghua2022@email.szu.edu.cn
I am looking forward to your email.

import nibabel as nib
import os
import numpy as np

path_in = r'H:\数据\新建文件夹\BraTS2020_TrainingData\MICCAI_BraTS2020_TrainingData'
path_out = r"H:\数据\新建文件夹\BraTS2020_croped_240"
start_second = True
list_four = [0,1,2,3,4]
num = 0


for root, dirs, files in os.walk(path_in):#root表示文件夹路径，dirs为空，files文件夹里的文件名
    print(num)
    num+=1
    if start_second == False:#because the first root is not right,so use the "start_second" just for drop out it
        for i in range(26, 75):
            file_name = os.path.split(root)
            nii_four = os.listdir(root)  # 0 1 2 3 4

            sub_dir = os.path.join(path_out, file_name[-1])
            sub_dir_add = "{}{}".format(sub_dir,"_"+str(i))
            os.mkdir(sub_dir_add)



            for j in list_four:
                sample_raw = nib.load(os.path.join(root,nii_four[j]))
                affine = sample_raw.affine.copy()
                hdr = sample_raw.header.copy()
                sample_np = np.asarray(sample_raw.get_fdata())
                sample_np = sample_np[:, :, i]
                gen = nib.Nifti1Image(sample_np, affine, hdr)

                rename = nii_four[j].split(".")
                rename = "{}_{}{}".format(rename[0],i,rename[1])
                nib.save(gen, os.path.join(sub_dir_add,rename))

    start_second = False

**Comment by guanzhenghua** [comment]
@saisusmitha of course, it is easy to slice 3D to 2D, i will show the code later.
I processed the data in the author's way, From the picture, it should be fine.
I'm sure the data preprocessing is fine, but the result does include a mixture of the original and the segmentation, so i wonder and need the author's answer. Have you run this program successfully.
maybe we can talk more in email: guanzhenghua2022@email.szu.edu.cn
I am looking forward to your email.
![image](https://user-images.githubusercontent.com/114739026/235576292-72d9357b-e8bc-44b4-8808-5e43fb864aae.png)
Copying the code directly will look strange, please forgive me for using the screenshot of the code.

**Comment by guanzhenghua** [comment]
@saisusmitha the author answer this question in #13, it is true thar the sampling result include the original image and mask, so in order to get perfert mask which is sampled by original image, should another operate that is add the threshold to separate the profile and the mask.
