### ISSUE TITLE
Visdom on SageMaker Studio Lab -> possible?

### ISSUE THREAD

**Issue by imruljubair** [JuliaWolleb/Diffusion-based-Segmentation#39]
Hi,
I do not have any local GPU, and I am using AWS SageMaker Studio Lab for running this code. I am able to run the code, but cannot utilize the Visdom on SageMaker Studio Lab, since I cannot find way to use browser there.

Can anyone help me regarding this?

Thanks in advance!
-
Jubair

**Comment by JuliaWolleb** [comment]
Hi

I am sorry i have no experience with the AWS SageMaker Studio Lab. However, training and validation should run without visdom. Visdom is only there for visualization purposes. You can replace it with any other visualization tool that runs on your framework.
