### ISSUE TITLE
The cut of 3D Slicers

### ISSUE THREAD

**Issue by smallboy-code** [JuliaWolleb/Diffusion-based-Segmentation#40]
Hi, @JuliaWolleb 
I have met a problem with the cut of 3D Slicers. What does "the lowest 80 slices and the uppermost 26 slices" mean? Maybe from 80 to 129 or from 26 to 75 in axial slicers. I look forward to your reply. Thank you!

**Comment by JuliaWolleb** [comment]
Hi

It means the axial slices 80 to 129, if you count from bottom to top.
