### ISSUE TITLE
Run on Multiple GPUS

### ISSUE THREAD

**Issue by TheRealCameronEvans** [JuliaWolleb/Diffusion-based-Segmentation#43]
Hello, thanks for sharing your code! Would it be possible for me to run the processes across multiple GPUs? I have a few low powered ones so this would speed my jobs up a lot. 
Thanks!

**Comment by JuliaWolleb** [comment]
Good morning

Yes, to run across multiple GPUs, this is already implemented in the code.
You will need to set the flag `use_ddp = True`, you will enter the torch DistributedDataParallel (DDP) in the file [guided_diffusion/train_util.py ](https://github.com/JuliaWolleb/Diffusion-based-Segmentation/blob/676f214035e90edd0357f51feab45841e4aefcfb/guided_diffusion/train_util.py#L108).

Let me know whether this answers your question.
Best,
Julia
