### ISSUE TITLE
Train with multiple classes

### ISSUE THREAD

**Issue by suhas-srinath** [JuliaWolleb/Diffusion-based-Segmentation#44]
Hi, thanks a lot for the code! I am interested in training with multiple segmentation classes, but some parts of the code convert the masks into binary masks. How does the training happen with multiple segmentation classes and what are the right parameter arguments for the same?

**Comment by JuliaWolleb** [comment]
Hi
If you have multiple classes, you will need a one-hot-encoding for the classes. For example, if you have 3 classes, you will have 3 output channels, each showing a binary mask for the respective class.
To change the number of output channels `(out_channels) in` the file [guided_diffusion/script_util.py](https://github.com/JuliaWolleb/Diffusion-based-Segmentation/blob/676f214035e90edd0357f51feab45841e4aefcfb/guided_diffusion/script_util.py#L170C4-L170C4) to 2*3=6. If you set the flag `learn_sigma=False`, set `out_channels=3`.

Let me know if you have further questions

**Comment by suhas-srinath** [comment]
Hi, thanks a lot for the response! I'm able to train it for 3 classes now.
