### ISSUE TITLE
Would you please public the code for make the Brats data into the slices you mentioned in the paper?

### ISSUE THREAD

**Issue by cqlouis** [JuliaWolleb/Diffusion-based-Segmentation#47]
The original Brtas2020 is 155*240*240, but the paper said it should be change into  slices with 5*240*240, Would you provide the code for that?
Thanks advanced!

**Comment by JuliaWolleb** [comment]
Hi
We sliced the 3D volume into 2D axial slices, and cropped them to a size of 224x224 (to cut some zero values around the brain).
We stack the input to 5 channels ( 4 for the different MR sequences, and 1 for the noisy segmentation mask).
