### ISSUE TITLE
Hello, why  did I have this problem during training

### ISSUE THREAD

**Issue by jaceqin** [JuliaWolleb/Diffusion-based-Segmentation#8]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8850): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B87FDB7FA0>: Failed to establish a new co
nnection: [WinError 10061] Unable to connect because the target computer actively refused。'))

**Comment by JuliaWolleb** [comment]
seems like a problem with visdom. is it still running?

**Comment by jaceqin** [comment]
OK.Thank you !
